version: '3.8'
services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - mysqldata:/var/lib/mysql
  server:
    build:
      context: .
      dockerfile: ./dockerfiles/apache.dockerfile
    volumes:
      - ./moodledata:/var/www/moodledata
    ports:
      - 80:80
    depends_on:
      - mysql
volumes:
  mysqldata: {}

